version: "3"

services:

  wiki:
    image: ghcr.io/requarks/wiki:${wiki_js_ver:-2}
    restart: always
    environment:
      TZ: Europe/Moscow
      DB_TYPE: postgres
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      WIKI_PORT: ${WIKI_PORT}
    ports:
      - "${WIKI_PORT}:3000"
    volumes:
      - wiki_temp:/wiki/data
      - /etc/localtime:/etc/localtime:ro
    
    # Label for Traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.wiki.rule=Host(`wiki.yc.cloudtechport.com`)
      - traefik.http.routers.wiki.entrypoints=https
      - traefik.http.routers.wiki.tls=true
      - traefik.http.routers.wiki.tls.certresolver=letsEncrypt
      - traefik.http.services.wiki.loadbalancer.server.port=3000
      - traefik.docker.network=web

    networks:
      - web # Traefik network

volumes:
  wiki_temp:

networks:
  web:
    external: true