version: "3"

x-log: &default
  restart: always
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "10"

x-env-general: &env-general
  TZ: ${TZ:-Europe/Moscow}

x-env-wiki: &env-wiki
  DB_HOST: ${DB_HOST:-db}
  DB_PORT: ${DB_PORT:-5432}
  DB_NAME: ${DB_NAME:-wiki}
  DB_USER: ${DB_USER:-wikijs}
  DB_PASS: ${DB_PASS:-wikijsrocks}
  DB_TYPE: ${DB_TYPE:-postgres}

x-env-db: &env-db
  POSTGRES_DB: ${DB_NAME:-wiki}
  POSTGRES_USER: ${DB_USER:-wikijs}
  POSTGRES_PASSWORD: ${DB_PASS:-wikijsrocks}

x-env-elasticsearch: &env-elasticsearch
  MAX_LOCKED_MEMORY: ${MAX_LOCKED_MEMORY:-unlimited}
  ELASTICSEARCH_NODE_NAME: ${ELASTICSEARCH_NODE_NAME:-1-elasticsearch-master}
  ELASTICSEARCH_CLUSTER_HOSTS: ${ELASTICSEARCH_CLUSTER_HOSTS:-1-elasticsearch-master}
  ELASTICSEARCH_CLUSTER_NAME: ${ELASTICSEARCH_CLUSTER_NAME:-elasticsearch-cluster-wiki}
  ELASTICSEARCH_HEAP_SIZE: ${ELASTICSEARCH_HEAP_SIZE:-1g}
  ELASTICSEARCH_MINIMUM_MASTER_NODES: ${ELASTICSEARCH_MINIMUM_MASTER_NODES:-1}

x-env-postgres-exporter: &env-postgres-exporter
  DATA_SOURCE_NAME: ${DATA_SOURCE_NAME:-postgresql://wikijs:wikijsrocks@db:5432/postgres?sslmode=disable"}

services:
  db:
    build: ./postgresql
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          memory: 50M
    security_opt:
      - no-new-privileges:true
    environment:
      <<: *env-db
      <<: *env-general
    <<: *default
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-dump:/dump
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  wiki:
    image: ghcr.io/requarks/wiki:2
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          memory: 50M 
    security_opt:
      - no-new-privileges:true
    environment:
      <<: *env-wiki
      <<: *env-general
    <<: *default
    ports:
      - ${WIKI_PORT:-8000}:3000
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    volumes:
      - wiki_temp:/wiki/data
    healthcheck:
      test: (curl http://localhost:3000/healthz | grep ok) || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: bitnami/elasticsearch:7.17.5
    hostname: "1-elasticsearch-master"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
        reservations:
          memory: 50M 
    security_opt:
      - no-new-privileges:true
    volumes:
      - elasticsearch-data:/bitnami/elasticsearch/data
    environment:
      <<: *env-elasticsearch
      <<: *env-general
    <<: *default
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1m

  elasticsearch-exporter:
    image: bitnami/elasticsearch-exporter:latest
    command:
      '--es.uri=http://elasticsearch:9200'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
        reservations:
          memory: 50M 
    security_opt:
      - no-new-privileges:true
    environment:
      <<: *env-general
    <<: *default
    ports:
      - ${ES_EX_PORT:-9114}:9114
    depends_on:
      elasticsearch:
        condition: service_healthy

  postgres-exporter:
    image: bitnami/postgres-exporter:latest
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
        reservations:
          memory: 50M 
    security_opt:
      - no-new-privileges:true
    environment:
      <<: *env-general
      <<: *env-postgres-exporter
    <<: *default
    ports:
      - ${DB_EX_PORT:-9187}:9187
    depends_on:
      db:
        condition: service_healthy

  db-backup:
    container_name: example-db-backup
    image: tiredofit/db-backup
    volumes:
      - ./backups:/backup
      #- ./post-script.sh:/assets/custom-scripts/post-script.sh
    environment:
      - DB_TYPE=pgsql
      - DB_HOST=db
      - DB_NAME=example
      - DB_USER=example
      - DB_PASS="examplepassword"
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - CHECKSUM=SHA1
      - COMPRESSION=ZSTD
      - SPLIT_DB=FALSE
    <<: *default

volumes:
  db-data:
  elasticsearch-data:
  wiki_temp: