version: "3"

x-log: &default
  restart: always
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "10"

services:
  db:
    image: postgres:12-alpine
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          memory: 50M 
    security_opt:
      - no-new-privileges:true
    env_file:
      - prod.env
    <<: *default
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5


  wiki:
    image: ghcr.io/requarks/wiki:2
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          memory: 50M 
    security_opt:
      - no-new-privileges:true
    env_file:
      - prod.env
    <<: *default
    ports:
      - "8000:3000"
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    volumes:
      - wiki_temp:/wiki/data
    healthcheck:
      test: (curl http://localhost:3000/healthz | grep ok) || exit 1
      interval: 10s
      timeout: 5s
      retries: 5





  elasticsearch:
    image: bitnami/elasticsearch:7.17.5
    hostname: "1-elasticsearch-master"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
        reservations:
          memory: 50M 
    security_opt:
      - no-new-privileges:true
    volumes:
      - elasticsearch-data:/bitnami/elasticsearch/data
    env_file:
      - prod.env
    <<: *default
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1m

  elasticsearch-exporter:
    image: bitnami/elasticsearch-exporter:latest
    command:
      '--es.uri=http://elasticsearch:9200'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
        reservations:
          memory: 50M 
    security_opt:
      - no-new-privileges:true
    env_file:
      - prod.env
    <<: *default
    ports:
      - "9114:9114"
    depends_on:
      - elasticsearch

  postgres-exporter:
    image: bitnami/postgres-exporter:latest
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
        reservations:
          memory: 50M 
    security_opt:
      - no-new-privileges:true
    env_file:
      - prod.env
    <<: *default
    ports:
      - "9187:9187"
    depends_on:
      - elasticsearch

volumes:
  db-data:
  elasticsearch-data:
  wiki_temp: